import numpy as np
import config

# This file contains the core physics calculations for the 6DOF rocket simulation, including aerodynamic forces, gravity, thrust, and the equations of motion. The main function is calculate_6dof_kinematics, which computes the linear and angular accelerations based on the current state of the rocket and its environment. The code also includes a safety check for excessive angle of attack during launch to prevent unrealistic behavior.

# quaternion to rotation matrix conversion
def quat_to_rot_matrix(quat):
    w, x, y, z = quat
    M = np.array([
        [1 - 2*y**2 - 2*z**2,     2*x*y - 2*w*z,         2*x*z + 2*w*y],
        [2*x*y + 2*w*z,           1 - 2*x**2 - 2*z**2,   2*y*z - 2*w*x],
        [2*x*z - 2*w*y,           2*y*z + 2*w*x,         1 - 2*x**2 - 2*y**2]
    ])
    return M

#Barrowman Center of Pressure Calculations
def calculate_aerodynamics(rocket, alpha_rads):
    cn_nose = 2.0                       # Normal force coefficient for the nose cone, assuming a conical shape. 
    cp_nose = 0.5 * rocket.nose_length  # Center of pressure for the nose cone, located at 50% of the nose length from the tip for a conical shape.
    S = rocket.fin_span
    Cr = rocket.fin_root_chord
    Ct = rocket.fin_tip_chord
    Lf = rocket.fin_sweep
    Xr = rocket.dist_to_fins

    k_fb = 1 + (R/ (S + R))             # Fin-body interference factor, which accounts for the interaction between the fins and the rocket body. 
    cn_fins_term1 = 4.0 * rocket.num_fins * (S / rocket.diameter_m)**2  # Term 1 calculates pure fin lifting surface area relative to the body diameter.
    cn_fins_term2 = 1.0 + np.sqrt(1.0 + (2.0 * Lf / (Cr + Ct))**2)      # Term 2 accounts for the effect of fin sweep on the normal force coefficient, which reduces the effective lift generated by the fins at higher angles of attack.
    cn_fins = k_fb * (cn_fins_term1 / cn_fins_term2)                    # The overall normal force coefficient for the fins, which combines the effects of fin area and sweep.

    # This locates the exact aerodynamic center (Mean Aerodynamic Chord) of the fin shape.
    # Xr shifts the starting point down the rocket, and the rest of the equation finds the specific balance point of the trapezoidal fin geometry.
    cp_fins = Xr + (Lf / 3.0) * ((Cr + 2.0 * Ct) / (Cr + Ct)) + (1.0 / 6.0) * ((Cr + Ct) - (Cr * Ct) / (Cr + Ct)) 


    cn_total = cn_nose + cn_fins                                      # Total normal force coefficient is the sum of the contributions from the nose and fins. 
    cp_total = ((cn_nose * cp_nose) + (cn_fins * cp_fins)) / cn_total # The overall center of pressure is a weighted average of the nose and fin centers of pressure, weighted by their respective normal force coefficients.

    return cn_total, cp_total

def calculate_6dof_kinematics(rocket, environment, pos, vel, quat, omega, current_thrust_n, current_mass_kg, current_cg, inertia_tensor):
    # Convert the 4D quaternion into a 3x3 rotation matrix to map Body coordinates to World coordinates.
    rot_matrix = quat_to_rot_matrix(quat)

    # Define which way the rocket's nose is actually pointing in the 3D world (assuming +Z is the nose in the body frame)
    rocket_pointing_dir = rot_matrix @ np.array([0, 0, 1])

    g = np.array([0, 0, -9.81])
    force_gravity = current_mass_kg * g
    speed = np.linalg.norm(vel)

    # Query the atmospheric model for exact air density and temperature at this specific altitude.
    rho = environment.get_density(pos[2])
    temp = environment.get_temperature(pos[2])
    
    # Calculate the localized Speed of Sound using the Ideal Gas formula (gamma * R * T)
    speed_of_sound = np.sqrt(1.4 * 287.05 * temp)

    # Determine the current Mach number to look up the correct drag coefficient from CSV curve.
    current_mach = speed / speed_of_sound

    if speed > 0.1:
        # Drag always acts in the exact opposite direction of your velocity vector.
        drag_dir = -vel / speed
        drag_coefficient = rocket.get_cd(current_mach)
        # Standard Drag Equation: Fd = 1/2 * rho * v^2 * Cd * A
        force_drag = 0.5 * rho * (speed**2) * drag_coefficient * rocket.reference_area * drag_dir
    else:
        # Prevent division by zero errors when the rocket is sitting perfectly still on the pad.
        force_drag = np.array([0.0, 0.0, 0.0])

    # Thrust vector is purely aligned with wherever the nose of the rocket is pointing.
    thrust_vec = rocket_pointing_dir * current_thrust_n
    
    # Newton's Second Law
    force_net = thrust_vec + force_gravity + force_drag

    # Ground Reaction Force: If the rocket is on the ground and gravity is pulling it down, zero out the downward force so it doesn't accelerate through the floor.
    if pos[2] <= 0 and force_net[2] < 0:
        force_net[2] = 0

    #Restructure Newton's Second Law to solve for acceleration: a = F/m
    acceleration = force_net / current_mass_kg

    # Get crosswind at certain altitude
    wind_vector = environment.get_wind_vector(pos[2])  

    # Vector subtraction: The air the rocket "feels" is its own velocity minus the wind's velocity.
    air_velocity = vel - wind_vector
    airspeed = np.linalg.norm(air_velocity)

    torque_net = np.array([0.0, 0.0, 0.0])  # Placeholder for net torque calculation

    if airspeed > 0.1 and vel[2] > 0:
        air_dir = air_velocity / airspeed
        # Dot product to find the angle between the rocket's pointing direction and where the air is hitting it from.
        cos_alpha = np.dot(rocket_pointing_dir, air_dir) 
        cos_alpha = np.clip(cos_alpha, -1.0, 1.0) # Prevent math domain errors from floating point inaccuracies.
        alpha = np.arccos(cos_alpha)

        # Safety check for tilt lockout if angle of attack exceeds a certain threshold.
        max_alpha_rad = np.radians(25) # <--- angle is customizable
        if alpha > max_alpha_rad and config.LAUNCH_RAIL_LENGTH_M < pos[2] < 100:
            import sys
            print("\n" + "="*50)
            print("🛑 TILT LOCKOUT TRIGGERED 🛑")
            print(f"Angle of Attack reached {np.degrees(alpha):.1f}° off the launch rail.")
            print("Safety limit exceeded (Max 15.0°). Launch aborted.")
            print("="*50 + "\n")
            sys.exit()

        cn_total, cp_total = calculate_aerodynamics(rocket, alpha)

        # Calculate the pure sideways force generated by the fins and body tube.
        normal_force_mag = 0.5 * rho * (airspeed**2) * cn_total * rocket.reference_area * alpha

        # Static Margin / Lever Arm: The distance between the Center of Pressure and Center of Gravity. (think of it like a seesaw where cg is the pivot point - if cp is far in front of cg, you get more leverage for stability but also more torque from wind gusts)
        lever_arm = cp_total - current_cg

        # Cross product determines the 3D axis that the wind is trying to rotate the rocket around. (right hand rule: if you point your right hand fingers in the direction of the rocket's nose and curl them towards the wind direction, your thumb will point in the direction of the axis that the rocket will want to rotate around due to the aerodynamic forces)
        torque_axis = np.cross(rocket_pointing_dir, air_dir)
        if np.linalg.norm(torque_axis) > 0.001:
            torque_axis = torque_axis / np.linalg.norm(torque_axis)
            # Torque = Force * Distance. This is the restoring force causing weathercocking
            torque_net = (normal_force_mag * lever_arm) * torque_axis

        # Map the rocket's local body spin into the global world frame.
        omega_inertial = rot_matrix @ omega

        # Accounting for imperfections in rocket that induce roll (fin cant etc.)
        cant_angle_rad = rocket.fin_cant_angle_rad

        fin_area = rocket.fin_span * (rocket.fin_root_chord + rocket.fin_tip_chord) / 2.0
        moment_arm = (rocket.diameter_m / 2.0) + (rocket.fin_span / 2.0)
        cl_alpha = 2.0 * np.pi # Coefficient of lift for fins
        q = 0.5 * rho * (airspeed**2) # Dynamic pressure

        # Isolate how fast the rocket is currently spinning along its central roll axis.
        w_roll = np.dot(omega_inertial, rocket_pointing_dir)
        
        # Calculate the aerodynamic lift generated by the canted fins (driving the roll).
        roll_force_per_fin = q * fin_area * cl_alpha * cant_angle_rad
        roll_driving_torque_mag = rocket.num_fins * roll_force_per_fin * moment_arm

        # Calculate the aerodynamic friction fighting against the spin (roll damping).
        roll_damping_torque_mag = -(rocket.num_fins * q * fin_area * cl_alpha * (moment_arm**2) * w_roll) / airspeed

        # Combine them to get the net roll torque vector.
        total_roll_torque_mag = roll_driving_torque_mag + roll_damping_torque_mag
        roll_torque_vec = total_roll_torque_mag * rocket_pointing_dir
        torque_net += roll_torque_vec

        # Calculate resistance against the rocket tumbling end-over-end. This acts like a shock absorber, keeping the flight stable.
        pitch_yaw_omega_inertial = omega_inertial - (w_roll * rocket_pointing_dir)
        damping_factor = 0.05 * rho * airspeed * rocket.reference_area * (rocket.dist_to_fins**2)
        pitch_yaw_damping_torque = -damping_factor * pitch_yaw_omega_inertial
        torque_net += pitch_yaw_damping_torque

        # Convert all the accumulated world-frame torques back into the rocket's local body frame.
        torque_net_body = rot_matrix.T @ torque_net
    else:
        # When moving very slowly, standard aerodynamics break down. Applied generic damping and a gentle gravity turn (pendulum effect) to point the heavy nose downward.
        damping_torque_body = -1.0 * omega
        target_dir = np.array([0.0, 0.0, -1.0])
        pendulum_torque_world = 1.0 * np.cross(rocket_pointing_dir, target_dir)
        pendulum_torque_body = rot_matrix.T @ pendulum_torque_world
        torque_net_body = damping_torque_body + pendulum_torque_body

    # Take the inverse of the 3x3 inertia matrix (which tracks how the mass is distributed).
    inertia_inv = np.linalg.inv(inertia_tensor)

    # Masses that are spinning experience a gyroscopic effect that resists changes to their orientation. This term captures that effect, which becomes more pronounced at higher spin rates.
    gyroscopic_torque = np.cross(omega, inertia_tensor @ omega)

    # Euler's Equations of Motion for Rigid Bodies: 
    angular_acceleration = inertia_inv @ (torque_net_body - gyroscopic_torque)

    # If the rocket's altitude is lower than the rail length, physically lock out any rotation. The rail forces it to fly perfectly straight regardless of wind or fin cant.
    launch_rail_length_m = config.LAUNCH_RAIL_LENGTH_M
    if pos[2] < launch_rail_length_m:
        angular_acceleration = np.array([0.0, 0.0, 0.0])

    return acceleration, angular_acceleration

